DELIMITER ENDROUTINE
CREATE FUNCTION get_name_of_database_user
(
      arg_party_name $PARTY_NAME_TYPE
)
RETURNS TEXT
LANGUAGE SQL
DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
    RETURN CONCAT('$DATABASE_USER_PREFIX', arg_party_name)
    ;
ENDROUTINE
DELIMITER ;
